
server:
  servlet:
    context-path: /promotion
  port: 8020

promotion:
  pattern:
    fullReduce: 购买至少(.*?)件时可享受优惠,满(.*?)元减(.*?)元
    # 多个满减
    multiFullReduce: 满(\d+).?减(\d+)
    fullSave: 满(.*?)元,省(.*?)元
    everyReduce1: 每(\d+)减(.*?),
    everyReduce2: 每满(.*?)元,省(.*?)元
    everyReduce3: 每满(.*?)元，可减(.*?)元现金，最多可减(.*?)元
    # 多个每减
    everyReduce4: 每满(.*?)元，可减(\d+)元现金
    discount1: 下单再享(.*?)折
    discount2: 满(.*?)件,打(.*?)折
    discount3: 满(.*?)享(.*?)折
    # 多个满折
    discount4: 满(\d+)件，总价打([1-9]\d*\.?\d*)|(0\.\d*[1-9])折
    # 未启用-混合折扣：可由其他促销策略组合实现
    mixDiscount1: 每(.*?)减(.*?),可跨店,上不封顶,满(.*?)件,打(.*?)折,
    # 未启用-多个混合：可由其他促销策略组合实现
    mixDiscount2: 满(.*?)元减(.*?)元，满(.*?)元减(.*?)元，满(.*?)元减(.*?)元,满(.*?)件，总价打(.*?)折；满(.*?)件，总价打(.*?)折,
    # 忽略处理
    ignore: 淘金币可抵(.*?)元起,
